/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  PwcFilter,
} from './utils/PwcFilter';

export namespace Components {
  interface PwcDynamicForm {
    'getFieldValues': (returnOnlyValuesForPwcSelects?: boolean) => Promise<{ [key: string]: string | boolean | string[]; }>;
  }
  interface PwcDynamicFormButtons {
    'items': string | PwcFilter.ButtonItemConfig[];
  }
  interface PwcDynamicFormContent {
    'items': string | PwcFilter.ContentItemConfig[];
  }
}

declare global {


  interface HTMLPwcDynamicFormElement extends Components.PwcDynamicForm, HTMLStencilElement {}
  var HTMLPwcDynamicFormElement: {
    prototype: HTMLPwcDynamicFormElement;
    new (): HTMLPwcDynamicFormElement;
  };

  interface HTMLPwcDynamicFormButtonsElement extends Components.PwcDynamicFormButtons, HTMLStencilElement {}
  var HTMLPwcDynamicFormButtonsElement: {
    prototype: HTMLPwcDynamicFormButtonsElement;
    new (): HTMLPwcDynamicFormButtonsElement;
  };

  interface HTMLPwcDynamicFormContentElement extends Components.PwcDynamicFormContent, HTMLStencilElement {}
  var HTMLPwcDynamicFormContentElement: {
    prototype: HTMLPwcDynamicFormContentElement;
    new (): HTMLPwcDynamicFormContentElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-dynamic-form': HTMLPwcDynamicFormElement;
    'pwc-dynamic-form-buttons': HTMLPwcDynamicFormButtonsElement;
    'pwc-dynamic-form-content': HTMLPwcDynamicFormContentElement;
  }
}

declare namespace LocalJSX {
  interface PwcDynamicForm {
    'onFormChanged'?: (event: CustomEvent<PwcFilter.FormChangedEventPayload>) => void;
  }
  interface PwcDynamicFormButtons {
    'items'?: string | PwcFilter.ButtonItemConfig[];
  }
  interface PwcDynamicFormContent {
    'items'?: string | PwcFilter.ContentItemConfig[];
    'onFieldChanged'?: (event: CustomEvent<PwcFilter.FieldChangedEventPayload>) => void;
  }

  interface IntrinsicElements {
    'pwc-dynamic-form': PwcDynamicForm;
    'pwc-dynamic-form-buttons': PwcDynamicFormButtons;
    'pwc-dynamic-form-content': PwcDynamicFormContent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-dynamic-form': LocalJSX.PwcDynamicForm & JSXBase.HTMLAttributes<HTMLPwcDynamicFormElement>;
      'pwc-dynamic-form-buttons': LocalJSX.PwcDynamicFormButtons & JSXBase.HTMLAttributes<HTMLPwcDynamicFormButtonsElement>;
      'pwc-dynamic-form-content': LocalJSX.PwcDynamicFormContent & JSXBase.HTMLAttributes<HTMLPwcDynamicFormContentElement>;
    }
  }
}


