/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PwcDynamicForm {
    'form': string;
  }
}

declare global {


  interface HTMLPwcDynamicFormElement extends Components.PwcDynamicForm, HTMLStencilElement {}
  var HTMLPwcDynamicFormElement: {
    prototype: HTMLPwcDynamicFormElement;
    new (): HTMLPwcDynamicFormElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-dynamic-form': HTMLPwcDynamicFormElement;
  }
}

declare namespace LocalJSX {
  interface PwcDynamicForm {
    'form'?: string;
  }

  interface IntrinsicElements {
    'pwc-dynamic-form': PwcDynamicForm;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-dynamic-form': LocalJSX.PwcDynamicForm & JSXBase.HTMLAttributes<HTMLPwcDynamicFormElement>;
    }
  }
}


